python:
  - changed-files:
    - any-glob-to-any-file: '**/*.py'

ui:
  - changed-files:
    - any-glob-to-any-file: 'ui/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements.txt'
      - 'pyproject.toml'
      - 'ui/package.json'
      - 'ui/package-lock.json'
